In [1]:
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt


In [2]:
dense = tf.keras.layers.Dense(
    units = 1,
    activation=None,
    use_bias=True,
    kernel_initializer=tf.keras.initializers.Zeros(),
    bias_initializer="zeros",
    kernel_regularizer=None,
    bias_regularizer=None,
    activity_regularizer=None,
    kernel_constraint=None,
    bias_constraint=None,

)


In [4]:
X = tf.constant([1,1,3])
X = tf.reshape(X,shape=(1,3,1))
X

<tf.Tensor: shape=(1, 3, 1), dtype=int32, numpy=
array([[[1],
        [1],
        [3]]], dtype=int32)>

In [5]:
dense(X)

<tf.Tensor: shape=(1, 3, 1), dtype=float32, numpy=
array([[[0.],
        [0.],
        [0.]]], dtype=float32)>