In [1]:
import os
import tensorflow as tf

In [2]:
# initialization of tensors 
x = tf.constant(4,shape = (3,3),dtype = tf.float32)
print(x)

tf.Tensor(
[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]], shape=(3, 3), dtype=float32)


2021-09-30 00:03:39.795162: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [3]:
x = tf.ones((3,3))
print(x)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [4]:
x = tf.zeros((10,10))
print(x)

tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]], shape=(10, 10), dtype=float32)


In [5]:
# eye for identical matrix
x = tf.eye(3)
print(x)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [6]:
# you can also use random distribution
x = tf.random.normal((3,3),mean = 0,stddev = 1)
print(x)

tf.Tensor(
[[ 1.3541243   1.1084508  -2.0484388 ]
 [ 0.63418984 -0.64969784  1.1877886 ]
 [-0.03086414 -0.14715293 -1.7347479 ]], shape=(3, 3), dtype=float32)


In [7]:
# you can also use random distribution 
x = tf.random.uniform((3,3,2),minval = 1,maxval = 3)
print(x)

tf.Tensor(
[[[2.583438  2.8356693]
  [1.3716342 2.8541682]
  [1.1496441 2.676001 ]]

 [[1.8278234 2.2762523]
  [1.3977785 2.926079 ]
  [2.8205755 2.4041636]]

 [[2.8852692 1.680069 ]
  [1.586941  2.103516 ]
  [1.6545196 1.613805 ]]], shape=(3, 3, 2), dtype=float32)


In [8]:
# you can also specify an vector using range
x = tf.range(start = 1,limit = 10,delta = 2)
print(x)


tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)
