In [1]:
import tensorflow as tf
from tensorflow import keras
import numpy as np


In [5]:
X = tf.constant(np.arange(1,101),shape = (1,10,10,1),dtype = tf.float32)
X

<tf.Tensor: shape=(1, 10, 10, 1), dtype=float32, numpy=
array([[[[  1.],
         [  2.],
         [  3.],
         [  4.],
         [  5.],
         [  6.],
         [  7.],
         [  8.],
         [  9.],
         [ 10.]],

        [[ 11.],
         [ 12.],
         [ 13.],
         [ 14.],
         [ 15.],
         [ 16.],
         [ 17.],
         [ 18.],
         [ 19.],
         [ 20.]],

        [[ 21.],
         [ 22.],
         [ 23.],
         [ 24.],
         [ 25.],
         [ 26.],
         [ 27.],
         [ 28.],
         [ 29.],
         [ 30.]],

        [[ 31.],
         [ 32.],
         [ 33.],
         [ 34.],
         [ 35.],
         [ 36.],
         [ 37.],
         [ 38.],
         [ 39.],
         [ 40.]],

        [[ 41.],
         [ 42.],
         [ 43.],
         [ 44.],
         [ 45.],
         [ 46.],
         [ 47.],
         [ 48.],
         [ 49.],
         [ 50.]],

        [[ 51.],
         [ 52.],
         [ 53.],
         [ 54.],
         [ 55.],

In [14]:
print(X.shape)
print(tf.squeeze(X, axis = (0,-1)))

(1, 10, 10, 1)
tf.Tensor(
[[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
 [ 11.  12.  13.  14.  15.  16.  17.  18.  19.  20.]
 [ 21.  22.  23.  24.  25.  26.  27.  28.  29.  30.]
 [ 31.  32.  33.  34.  35.  36.  37.  38.  39.  40.]
 [ 41.  42.  43.  44.  45.  46.  47.  48.  49.  50.]
 [ 51.  52.  53.  54.  55.  56.  57.  58.  59.  60.]
 [ 61.  62.  63.  64.  65.  66.  67.  68.  69.  70.]
 [ 71.  72.  73.  74.  75.  76.  77.  78.  79.  80.]
 [ 81.  82.  83.  84.  85.  86.  87.  88.  89.  90.]
 [ 91.  92.  93.  94.  95.  96.  97.  98.  99. 100.]], shape=(10, 10), dtype=float32)


In [15]:
flat_layer = keras.layers.Flatten()
flat_layer(X)

<tf.Tensor: shape=(1, 100), dtype=float32, numpy=
array([[  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
         12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
         23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
         34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
         45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
         56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
         67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
         78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
         89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
        100.]], dtype=float32)>

In [10]:
X = tf.constant(np.random.randint(low=0,high=10,size=54),dtype=tf.int32)
X = tf.reshape(X,shape=(2,3,3,3))
print(X)
flat_layer = keras.layers.Flatten()
flat_layer(X)

tf.Tensor(
[[[[6 5 1]
   [6 5 4]
   [1 9 3]]

  [[8 3 2]
   [3 1 3]
   [0 4 5]]

  [[3 2 9]
   [2 6 4]
   [6 9 8]]]


 [[[9 5 9]
   [3 5 8]
   [3 0 9]]

  [[3 0 1]
   [7 9 2]
   [4 9 5]]

  [[0 3 2]
   [7 3 0]
   [1 7 5]]]], shape=(2, 3, 3, 3), dtype=int32)


<tf.Tensor: shape=(2, 27), dtype=int32, numpy=
array([[6, 5, 1, 6, 5, 4, 1, 9, 3, 8, 3, 2, 3, 1, 3, 0, 4, 5, 3, 2, 9, 2,
        6, 4, 6, 9, 8],
       [9, 5, 9, 3, 5, 8, 3, 0, 9, 3, 0, 1, 7, 9, 2, 4, 9, 5, 0, 3, 2, 7,
        3, 0, 1, 7, 5]])>