In [1]:
import tensorflow as tf
import numpy as np

In [12]:
x = tf.constant(np.array([1,2,3,4,5],dtype = 'float'))
with tf.GradientTape()as tape:
    tape.watch(x)
    y = x ** 2
dy_dx = tape.gradient(y,x)
dy_dx

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([ 2.,  4.,  6.,  8., 10.])>

In [2]:
w = tf.Variable(tf.random.normal((3, 2)), name='w')
b = tf.Variable(tf.zeros(2, dtype=tf.float32), name='b')
x = [[1., 2., 3.]]


2022-01-29 22:38:59.622408: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [6]:
print(w)
print(x)
print(x @ w)


<tf.Variable 'w:0' shape=(3, 2) dtype=float32, numpy=
array([[-0.49815235,  0.07702189],
       [ 0.27149647,  1.1403186 ],
       [ 0.7137109 , -0.87145215]], dtype=float32)>
[[1.0, 2.0, 3.0]]
tf.Tensor([[ 2.1859734  -0.25669742]], shape=(1, 2), dtype=float32)


TypeError: __array__() takes 1 positional argument but 2 were given