In [2]:
import numpy as np

In [9]:
# build and extract a matrix
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix[0:1,0:1])   

[[1]]


In [10]:
# special matrices
## identity matrix
i = np.eye(3)
print(i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
# special matrices
## np.zeros() / ones()
zero = np.zeros((5,5))
print(zero)
## here is a catch, using the eye(), we mean martix in default but not for zore,numpy
## which we must tell the shape of the matix 

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
