In [1]:
import numpy as np

## Definition of Dot product
> A dot product is the product of the magnitude of the vectors and the cos of the angle between them.
- $a . b = |a|.|b| cos \theta$

## Definition of Cross product
> A cross product is the product of the magnitude of the vectors and the sine of the angle that they subtend on each other.

In [2]:
a = np.array([1,2,3])
b = np.array([4,5,6])
# first the element wise multiplication
print("the element wise multiplication is :", a * b)

# the dot product produce a scalar the measure the |a||b|cos(theta)
print("the dot product of two vector is :", np.dot(a,b))
# here is another way to get dot product of two vector
print("another way to dot product:",a @ b)


# cross product produce a vector, remember, this vector is perpendicular to the surface by a & b
# and the magnitude of the vector is the area of that quadrangle
print(np.cross(a,b))


the element wise multiplication is : [ 4 10 18]
the dot product of two vector is : 32
another way to dot product: 32
[-3  6 -3]


In [25]:
a = np.mat([1,2,3])
b = np.mat([3,4,5])
print('a=',a,'\n','b =',b,'\n','b.T=\n',b.T)
#print("a matmul b get erro,:",np.matmul(a,b))
print("a matmul b.T = \n", np.matmul(a,b.T))
print("a.T matmul b = \n",np.matmul(a.T,b))


a= [[1 2 3]] 
 b = [[3 4 5]] 
 b.T=
 [[3]
 [4]
 [5]]
a matmul b.T = 
 [[26]]
a.T matmul b = 
 [[ 3  4  5]
 [ 6  8 10]
 [ 9 12 15]]
