In [1]:
import numpy as np

2*2 matrix dot 1*2 vector

In [3]:
a = np.array([-1,2])
b = np.array([[3,1],[1,2]])
print(a)
print(b)


[-1  2]
[[3 1]
 [1 2]]


In [4]:
b.dot(a) 

array([-1,  3])

In [9]:
ihat = b[:,0] #i hat 
jhat = b[:,1] #j hat 
result = a[0] * ihat + a[1] * jhat
print(result)

[-1  3]


[0,-1]
[1,0]
这个矩阵的作用是向左旋转90度

In [19]:
left_rotate = np.array([[0,-1],[1,0]])
a = np.array([1, 1])
left_rotate.dot(a)


array([-1,  1])

to shear the vector
[1,1]
[0,1]
这个矩阵将jhat推到了(1,1)，同时ihat不变

In [17]:
shear_jhat = np.array([[1,1],[0,1]])
a = np.array([1,1])
shear_jhat.dot(a)

array([2, 1])

接下来我们来看shear_yhat 与 left_rotate这两个变换顺序是否有关系

In [20]:
a = np.array([1,1])
print(shear_jhat.dot(left_rotate.dot(a)))
print(left_rotate.dot(shear_jhat.dot(a)))
# 可以看出，顺序不同，结果也不同   

[0 1]
[-1  2]


[1,1]   [0,-1]     [1,-1]
[0,1]   [1,0]   =   [1,0]