In [2]:
import math 
import numpy as np


In [ ]:
a = np.array([3,2])
b = np.array([1,3])

mat = np.mat([a,b])
mat_t = mat.T

print(mat)
print(mat_t)

In [ ]:
# 可以看出向量无论怎么放，其决定式都是一样的
r1 = np.linalg.det(mat)
r2 = np.linalg.det(mat_t)

print(r1,r2)

In [7]:
# 叉乘的意义
a = np.array([2,0,0])
b = np.array([0,2,0])
c = np.array([0,0,2])

# a x b 为 向量a b 组成的四边形的有向面积，换句话说就是一个向量，该向量的模是面积，方向垂直于该平面
print(np.cross(a,b))

# 而a b向量组成的平面的法向量就是
print(np.cross(a,b)/np.linalg.norm(np.cross(a,b)))

[0 0 4]
[0. 0. 1.]


In [ ]:
# 那我们需要思考的时，一个矩阵的逆矩阵，其决定式时多少呢
mat_inv = np.linalg.inv(mat)
print(np.linalg.det(mat_inv))
print(1/7)
print(np.linalg.det(mat))

In [11]:
#叉积的作用1：计算六面体的体积
a = np.array([2,3,1])
b = np.array([5,2,1])
c = np.array([-1,0,2])

mat = np.mat([a,b,c])
print(mat)
print(np.linalg.det(mat))


# 那么如何用向量来计算体积呢

norm_ab = np.cross(a,b) / np.linalg.norm(np.cross(a,b))  # 首先得到ab 平面的法向量
area_ab = np.linalg.norm(np.cross(a,b)) # 相当于底面积
print("ab平面的法向量是",norm_ab)
print(np.dot(c,norm_ab) * area_ab)

[[ 2  3  1]
 [ 5  2  1]
 [-1  0  2]]
-23.0
ab平面的法向量是 [ 0.08737041  0.26211122 -0.96107446]
-23.0


In [12]:
# 叉积的作用2 ： 判断点是否共面
## 这个很好理解，如果有其体积不为0，则3个点一定不共面



0.9999999999999999