In [2]:
import tensorflow as tf

In [4]:
x = tf.constant([1,2,3])
y = tf.constant([9,8,7])


tf.Tensor([10 10 10], shape=(3,), dtype=int32)
tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [5]:
z = tf.add(x,y)
print(z)
print(x+y)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)
tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [7]:
z = tf.subtract(y,x)
print(z)
print(y-x)

tf.Tensor([8 6 4], shape=(3,), dtype=int32)
tf.Tensor([8 6 4], shape=(3,), dtype=int32)


In [10]:
z = tf.multiply(x,y)
print(z)
print(x*y)


tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)
tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)


In [11]:
z = tf.divide(x,y)
print(z)
print(x/y)

tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)
tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)


In [15]:
z = tf.tensordot(x,y,axes = 1)
print(z)

tf.Tensor(46, shape=(), dtype=int32)
