In [1]:
import tensorflow as tf
import numpy as np

- rank of tensors
- similar to the demension of data

In [4]:
rank_tensor_0 = tf.Variable("hello",tf.string)
print(rank_tensor_0)
print(tf.rank(rank_tensor_0))

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'hello'>
tf.Tensor(0, shape=(), dtype=int32)


In [14]:
rank_tensor_1 = tf.Variable(["hello"],tf.string)
print(rank_tensor_1)
print(tf.rank(rank_tensor_1))

<tf.Variable 'Variable:0' shape=(1,) dtype=string, numpy=array([b'hello'], dtype=object)>
tf.Tensor(1, shape=(), dtype=int32)


In [15]:
rank_tensor_2 = tf.Variable([["hello","ij"],["jji","c"]],tf.string)
print(rank_tensor_2)
tf.rank(rank_tensor_2)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=string, numpy=
array([[b'hello', b'ij'],
       [b'jji', b'c']], dtype=object)>


<tf.Tensor: shape=(), dtype=int32, numpy=2>

 - shapes of tensor
 - amount of elements of each dimension

In [16]:
 rank_tensor_2.shape

TensorShape([2, 2])

- change the shape of the tensor 

In [27]:
tensor1 = tf.ones([3,2,4])
print(tensor1)
tensor2 = tf.reshape(tensor1,[3,4,2])
print(tensor2)
tensor3 = tf.reshape(tensor1,[4,2,3])
print(tensor3)

tf.Tensor(
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]], shape=(3, 2, 4), dtype=float32)
tf.Tensor(
[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]], shape=(3, 4, 2), dtype=float32)
tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]], shape=(4, 2, 3), dtype=float32)


In [ ]:
- lazy reshape
- use -1 to tell tensorflow that you need the tensorflow to calculate the number

In [30]:
tensor1 = tf.ones([3,2,4])
print(tensor1)
tensor2 = tf.reshape(tensor1,[4,2,-1])
print(tensor2)

tf.Tensor(
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]], shape=(3, 2, 4), dtype=float32)
tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]], shape=(4, 2, 3), dtype=float32)


- types of tensors
    - variable  # only this type of tensor can be changed durging execution
    - constant
    - placeholder
    - sparsetensor