In [3]:
import numpy as np

In [9]:
a1 = np.array([[1,0],[0,1]])
a2 = a1 * 2
print(a1)
print(a2)
print(np.linalg.det(a1))
print(np.linalg.det(a2))


[[1 0]
 [0 1]]
[[2 0]
 [0 2]]
1.0
4.0


In [4]:
# 矩阵的定义
a = np.mat([[1,2,3],[4,5,6]])
a

matrix([[1, 2, 3],
        [4, 5, 6]])

矩阵的乘法
$c_{ij} = \sum_{k=1}^{s}a_{ik}b_{kj}$

# 协方差的定义

$\frac{\sum{(x-\hat{x})(y-\hat{y})}}{n-1}\\$

In [19]:
rand = np.random.randn(4)
rand = rand.reshape((2,2))
print(rand)
np.cov(rand)

[[-0.98149893  0.82085594]
 [-0.15031931  1.39645792]]


array([[1.62424155, 1.39392074],
       [1.39392074, 1.1962599 ]])

In [22]:
# 矩阵的逆
a = np.array([[0,-1],[1,0]])
np.linalg.inv(a)

array([[ 0.,  1.],
       [-1., -0.]])

# 理解解方程组

$$
\begin{cases}
    a_{1}x + b_{1}y = c_{1}\\
    a_{2}x + b_{2}y = c_{2}
\end{cases}
$$

等同于
$$
\begin{bmatrix}
a_{1} & b_{1} \\ 
a_{2} & b_{2}
\end{bmatrix}

\begin{bmatrix}
x\\
y
\end{bmatrix}

=
\begin{bmatrix}
c_{1}\\
c_{2}
\end{bmatrix}
$$

那么
$$

\begin{bmatrix}
x\\
y
\end{bmatrix}

=
\begin{bmatrix}
c_{1}\\
c_{2}
\end{bmatrix}

\begin{bmatrix}
a_{1} & b_{1} \\ 
a_{2} & b_{2}
\end{bmatrix}^{-1}

$$

In [24]:
# 解方程组
#2x + y = 3
#x + y = 2
D1 = np.array([[2,1],[1,1]])
D2 = np.array([3,2])

result = np.dot(np.linalg.inv(D1),D2)
result

array([1., 1.])