In [2]:
import tensorflow as tf
import numpy as np
print(tf.__version__)

2.6.0


# tf.constant & ndim

In [4]:
# create a tensor with tf.constant
scalar = tf.constant(7)
print(scalar)

tf.Tensor(7, shape=(), dtype=int32)


In [5]:
# check the dimension of a scalar tensor using the ndim
scalar.ndim

0

In [6]:
# create a vector using tf.constant
vector = tf.constant([1,2,3])
vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [7]:
# check the dimension of our vector
vector.ndim

1

In [18]:
# create a matrix using tf.constant
matrix = tf.constant([[1,2,3],[4,5,6]],dtype=tf.float16)
print(matrix)
print("\n the ndim of your tensor is {}.".format(matrix.ndim))
print("\n the shape of your tensor is {}.".format(matrix.shape))

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float16)

 the ndim of your tensor is 2.

 the shape of your tensor is (2, 3).


In [24]:
# to recap, ndim is actually the length of the shape
# you should also notice that np.array similarly has attribute of ndim and shape
array = np.arange(start = 1, stop = 10, step = 1)
print(array,'\n')
print('the shape of array:' ,array.shape)
print('the dimension of array:',array.ndim)
# let's reshape the ndarray
array_reshaped = np.reshape(array,(3,3)) #(3,3) is the new shape of the array
print('the shape of the reshaped array is {}.'.format(array_reshaped.shape))
print('the ndim of the reshaped array is {}.'.format(array_reshaped.ndim))

[1 2 3 4 5 6 7 8 9] 

the shape of array: (9,)
the dimension of array: 1
the shape of the reshaped array is (3, 3).
the ndim of the reshaped array is 2.


# tf.Variable & assign

In [14]:
# tf.variable is the changable version of tensor
changeable_tensor = tf.Variable([[1,2],[3,4]])
unchangeable_tensor = tf.constant([1,2])

# first the tensor can be indexed by [][]
print(changeable_tensor)
print('the first element of changeable tensor is :{}'.format(changeable_tensor[0][0]))
print('the last element of changeable tensor is :{}'.format(changeable_tensor[1][1]))

# the item-wise assign fail , but I can reassin the whole thing
changeable_tensor.assign(np.array([[3,4],[5,6]]))


<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>
the first element of changeable tensor is :1
the last element of changeable tensor is :4


<tf.Variable 'UnreadVariable' shape=(2, 2) dtype=int32, numpy=
array([[3, 4],
       [5, 6]], dtype=int32)>

# creating random tensors

In [20]:
# create two but the same tensor /psudo random number

## use the same generator twice will cause different tensor 
generator = tf.random.Generator.from_seed(12)
random1 = generator.normal(shape = (3,3))
random2 = generator.normal(shape = (3,3))
print("random1 tensor is :{}".format(random1))
print("random2 tensor is :{}".format(random2))
print(random1 == random2)  # this operation will get the bool matrix

# use the same but different piece of generator will generate same entity
generator3 = tf.random.Generator.from_seed(12)
generator4 = tf.random.Generator.from_seed(12)
random3 = generator3.normal(shape=(3, 3))
random4 = generator4.normal(shape=(3, 3))
print("random3 tensor is :{}".format(random3))
print("random4 tensor is :{}".format(random4))
print(random3 == random4)


random1 tensor is :[[-1.0130816   0.28291714  1.2132233 ]
 [ 0.46988967  0.37944323 -0.6664026 ]
 [ 0.6054596   0.19181173  0.8045827 ]]
random2 tensor is :[[ 0.6660277   1.3501992   1.8031954 ]
 [ 1.4226911   0.04117621  1.3548882 ]
 [-1.3288164  -0.88940024  0.30758014]]
tf.Tensor(
[[False False False]
 [False False False]
 [False False False]], shape=(3, 3), dtype=bool)
random3 tensor is :[[-1.0130816   0.28291714  1.2132233 ]
 [ 0.46988967  0.37944323 -0.6664026 ]
 [ 0.6054596   0.19181173  0.8045827 ]]
random4 tensor is :[[-1.0130816   0.28291714  1.2132233 ]
 [ 0.46988967  0.37944323 -0.6664026 ]
 [ 0.6054596   0.19181173  0.8045827 ]]
tf.Tensor(
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]], shape=(3, 3), dtype=bool)
