In [ ]:
import tensorflow as tf
import numpy as np
print(tf.__version__)

# tf.constant & ndim

In [ ]:
# create a tensor with tf.constant
scalar = tf.constant(7)
print(scalar)

In [ ]:
# check the dimension of a scalar tensor using the ndim
scalar.ndim

In [ ]:
# create a vector using tf.constant
vector = tf.constant([1,2,3])
vector

In [ ]:
# check the dimension of our vector
vector.ndim

In [ ]:
# create a matrix using tf.constant
matrix = tf.constant([[1,2,3],[4,5,6]],dtype=tf.float16)
print(matrix)
print("\n the ndim of your tensor is {}.".format(matrix.ndim))
print("\n the shape of your tensor is {}.".format(matrix.shape))

# tensor & ndarray(numpy)

In [ ]:
# to recap, ndim is actually the length of the shape
# you should also notice that np.array similarly has attribute of ndim and shape
array = np.arange(start = 1, stop = 10, step = 1)
print(array,'\n')
print('the shape of array:' ,array.shape)
print('the dimension of array:',array.ndim)
# let's reshape the ndarray
array_reshaped = np.reshape(array,(3,3)) #(3,3) is the new shape of the array
print('the shape of the reshaped array is {}.'.format(array_reshaped.shape))
print('the ndim of the reshaped array is {}.'.format(array_reshaped.ndim))

In [ ]:
# you can use tensor.numpy() to convert tensor to ndarray
tensor_to_ndarray = tf.constant([[1,2,3],[4,5,6]])
tensor_to_ndarray.numpy()

# tf.Variable & assign

In [ ]:
# tf.variable is the changable version of tensor
changeable_tensor = tf.Variable([[1,2],[3,4]])
unchangeable_tensor = tf.constant([1,2])

# first the tensor can be indexed by [][]
print(changeable_tensor)
print('the first element of changeable tensor is :{}'.format(changeable_tensor[0][0]))
print('the last element of changeable tensor is :{}'.format(changeable_tensor[1][1]))

# the item-wise assign fail , but I can reassin the whole thing
changeable_tensor.assign(np.array([[3,4],[5,6]]))


# creating random tensors

In [ ]:
# create two but the same tensor /psudo random number

## use the same generator twice will cause different tensor 
generator = tf.random.Generator.from_seed(12)
random1 = generator.normal(shape = (3,3))
random2 = generator.normal(shape = (3,3))
print("random1 tensor is :{}".format(random1))
print("random2 tensor is :{}".format(random2))
print(random1 == random2)  # this operation will get the bool matrix

# use the same but different piece of generator will generate same entity
generator3 = tf.random.Generator.from_seed(12)
generator4 = tf.random.Generator.from_seed(12)
random3 = generator3.normal(shape=(3, 3))
random4 = generator4.normal(shape=(3, 3))
print("random3 tensor is :{}".format(random3))
print("random4 tensor is :{}".format(random4))
print(random3 == random4)


# shuffle & first dimension
## understand the order of shape(dimension)

In [ ]:
tensor_to_shuffle = tf.constant([
                                [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]], 
                                [[10, 20, 30], [40, 50, 60], [70, 80, 90], [100, 110, 120]],
                                [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]
                                ])
print("the shape of tensor is:",tensor_to_shuffle.shape)
print("the ndim of tensor is :",tensor_to_shuffle.ndim)
print("tensor_to_shuffle:",tensor_to_shuffle)

tensor_shuffled = tf.random.shuffle(tensor_to_shuffle)
print("tensor_shuffled:",tensor_shuffled)

# please note that shuffle function will only shuffle the first dimension of the tensor


# other ways to create tensor

In [ ]:
tensor_onses = tf.ones(shape = (4,4))
print(tensor_onses)
tensor_zeros = tf.zeros(shape = (4,4))
print(tensor_zeros)

# manipulate the tensor

In [ ]:
# concert a tensor from numpy array, and reshepe it!
np_array = np.arange(0,10,dtype=np.int32)
tensor = tf.constant(np_array)
tensor_shape1 = tf.constant(np_array,shape = (2,5))
print("tensor_shape1:",tensor_shape1)
# now index the tensor, every first dimension of with last element of the last dimension
print("slicing the tensor is :",tensor_shape1[:,-1])

# now add an extra dimension to our 2-dimension tensor
tensor_shape2 = tensor_shape1[:,:,tf.newaxis]
print("our tensor with extra  dimension is :",tensor_shape2)
print("it's shape is :",tensor_shape2.shape)

# here is another annotation to add another 
tensor_shape3 = tensor_shape1[..., tf.newaxis] # the annotation of ... stand for every dimension before
print("our tensor with extra  dimension is :", tensor_shape3)
print("it's shape is :", tensor_shape3.shape)


tensor_shape3 = tensor_shape1[:,tf.newaxis,:]
print("our tensor with extra  dimension is :",tensor_shape3)
print("it's shape is :",tensor_shape3.shape)

# alternative to tf.newaxis: tf.expand_dims()

tensor_shape4 = tf.expand_dims(tensor,axis = -1) # axis = -1 means to expand a new dimension in the last dimension(axis)
print("expand dimension using tf.expand_dims():",tensor_shape4)
print("thes shape of new tensor:",tensor_shape4.shape)

In [22]:
# martix multiplication
tensor1 = tf.constant([[1,2],[3,4]])
tensor2 = tf.constant([[1, 2], [3, 4]])
tensor3 = tf.constant(np.identity(3))
print(tensor1)
print(tensor2)

print("tensor1 dot(@) tensor2 = ",tensor1 @ tensor2)
print("tensor1 * tensor2 = ", tensor1 * tensor2)



tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tensor1 dot(@) tensor2 =  tf.Tensor(
[[ 7 10]
 [15 22]], shape=(2, 2), dtype=int32)
tensor1 * tensor2 =  tf.Tensor(
[[ 1  4]
 [ 9 16]], shape=(2, 2), dtype=int32)


In [20]:
a = np.array([1,2,3])
b = np.array([2,3,4])
print(a * b) # this type of multiplication is element-wise
print(np.dot(a * b)) # this is the dot pr

20