In [2]:
import tensorflow as tf
import numpy as np

tf.one_hot(
    indices, depth, on_value=None, off_value=None, axis=None, dtype=None, name=None
)

In [13]:
# If indices is a scalar the output shape will be a vector of length depth
indices = 10
print(tf.one_hot(indices,depth = 5,on_value="hello",off_value="world"))

tf.Tensor([b'world' b'world' b'world' b'world' b'world'], shape=(5,), dtype=string)


In [15]:
# If indices is a vector of length features, the output shape will be:
# features x depth if axis == -1
# depth x features if axis == 0
indices = [1,2,3]
print(tf.one_hot(indices, depth=5, axis=-1))
print(tf.one_hot(indices, depth=5, axis=0))
# 这里需要理解一下，aixs的意义，相当于扩展向量的维度

tf.Tensor(
[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]], shape=(3, 5), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]], shape=(5, 3), dtype=float32)


In [17]:
# if indices is a matrix(batch) with shape[batch, features], the output shape will be:
# batch x features x depth if axis == -1
# batch x depth x features if axis == 1
# depth x batch x features if axis == 0
# 这里可以比较明确地看出来axis 意味着新的维度（depth）插入的位置
indices = [[1,2],[3,1]]
print(tf.one_hot(indices, depth=4, axis=-1))
print(tf.one_hot(indices, depth=4, axis= 1))
print(tf.one_hot(indices, depth=4, axis= 0))


tf.Tensor(
[[[0. 1. 0. 0.]
  [0. 0. 1. 0.]]

 [[0. 0. 0. 1.]
  [0. 1. 0. 0.]]], shape=(2, 2, 4), dtype=float32)
tf.Tensor(
[[[0. 0.]
  [1. 0.]
  [0. 1.]
  [0. 0.]]

 [[0. 0.]
  [0. 1.]
  [0. 0.]
  [1. 0.]]], shape=(2, 4, 2), dtype=float32)
tf.Tensor(
[[[0. 0.]
  [0. 0.]]

 [[1. 0.]
  [0. 1.]]

 [[0. 1.]
  [0. 0.]]

 [[0. 0.]
  [1. 0.]]], shape=(4, 2, 2), dtype=float32)
