In [11]:
import tensorflow as tf
import numpy as np
import math 

In [3]:
# create a new tensor
a = tf.constant(np.arange(start = 1,stop = 11,step = 1))
a

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])>

In [5]:
# square the tensor
print("original tensor is :\n",a)
print("\n squared tensor is:\n",tf.math.square(a))

original tensor is :
 tf.Tensor([ 1  2  3  4  5  6  7  8  9 10], shape=(10,), dtype=int64)

 squared tensor is:
 tf.Tensor([  1   4   9  16  25  36  49  64  81 100], shape=(10,), dtype=int64)


In [7]:
# square root of tensor
print("original tensor is :\n", a)
print("\n squared tensor is:\n", tf.math.sqrt(tf.cast(a,dtype = tf.float32)))
# sqrt need dtype to be float, so you should use cast function to change the dtye

original tensor is :
 tf.Tensor([ 1  2  3  4  5  6  7  8  9 10], shape=(10,), dtype=int64)

 squared tensor is:
 tf.Tensor(
[0.99999994 1.4142134  1.7320508  1.9999999  2.236068   2.4494896
 2.6457512  2.8284268  3.         3.1622777 ], shape=(10,), dtype=float32)


In [9]:
# tf.math.less : Returns the truth value of (x < y) element-wise.
print('to figure out the truth of < 5 :\n', tf.math.less(a,5))

to figure out the truth of < 5 :
 tf.Tensor([ True  True  True  True False False False False False False], shape=(10,), dtype=bool)


In [30]:
# tf.math.log function deault base is e
print(tf.math.log([math.e]))
print("the original tensor is :\n",a)
print("the log of the tensor is :\n",tf.math.log(tf.cast(a,dtype = tf.float64)))
print('\n',[math.log(i+1) for i in range(10)]) # calculate the ln(x) using math

## calculate log2(x)
print("the original tensor is :\n",a)
print("the log2(x) of the tensor is :\n",tf.math.log(tf.cast(a,dtype = tf.float32))/math.log(2))
print('\n',[math.log(i+1)/math.log(2) for i in range(10)]) 
print('\n', [math.log2(i+1) for i in range(10)])

tf.Tensor([0.99999994], shape=(1,), dtype=float32)
the original tensor is :
 tf.Tensor([ 1  2  3  4  5  6  7  8  9 10], shape=(10,), dtype=int64)
the log of the tensor is :
 tf.Tensor(
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509], shape=(10,), dtype=float64)

 [0.0, 0.6931471805599453, 1.0986122886681098, 1.3862943611198906, 1.6094379124341003, 1.791759469228055, 1.9459101490553132, 2.0794415416798357, 2.1972245773362196, 2.302585092994046]
the original tensor is :
 tf.Tensor([ 1  2  3  4  5  6  7  8  9 10], shape=(10,), dtype=int64)
the log2(x) of the tensor is :
 tf.Tensor(
[0.        1.        1.5849625 2.        2.321928  2.5849626 2.807355
 3.        3.169925  3.321928 ], shape=(10,), dtype=float32)

 [0.0, 1.0, 1.5849625007211563, 2.0, 2.321928094887362, 2.584962500721156, 2.807354922057604, 3.0, 3.1699250014423126, 3.3219280948873626]

 [0.0, 1.0, 1.584962500721156, 2.0, 2.321928094887362, 2.584962500721156, 2.8